language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
script:
- "./gradlew clean build"
notifications:
  slack:
    rooms:
      secure: OIjS+rtvLXxLsS05wVMSqV0ic5E2IQAmINgMN7XJgfoYjgaJEcoFs8b43feDlaf9+ySd4/Z+dRQEFPvo30ZKYwW/OMim6d6d1CBtPICfohA/0bXRhrUR+SRSYpWZn8HAaQp4AXCTRfqq6IFyFWMP0+Y4FYJIqhbgwrhshHDlvRnx/62ZPplR1OIyKnCaLwYX1sjzOtMj1Y9rRPQb/Rg1NHcu9FbaX2GNYTrMPWPzhEGhS+R4wpOJ2ZDg4UwWnivKOUxgDt0dDURLSeSK80TVJz9AQwRAsGKzwNc2+rLxATkv68SjRdIxJgTnvySA9p/k1wR1eAIob7UPdjKNNnF5DS+u7NKNWcTSZNr6cS7VoqhxU23tIp7bJHyKcgBswl7IyZfo/zBvAcF5hocF1Y3FSGFOFMYSbA9EX/uXXDc26F+X3+GHoABhgn3X9c4L1VQLlSWYOW6UfQY7YidY+WW/oFqBikjQRqwrFDLNXbkkf3tlNZcA2iY28HJb5NX/JBY3A4RAfIHYQxEXeMOljSkKlGmse5ns5bJAa9OQdLxfPpmy071LVOu1QLo+RS1gDEFbVmWqwOHvBJE5XSlWw4l1Sq8QyL0Gcraqt6P6Ol9IX/3klysGaRWM3pLaNiP/p/2NTamJKTwUTFQG8BBV6KsJXl262mBkYC/GtXpcyrWi2hs=
deploy:
  provider : heroku
  api_key:
    secure: TtDwFDLwTfpfmy3iF5S/qET6a0x4VAKV8tfErMoZvavme93SQaroGbEK3TAHLUHkkyEMusw0bF6Nm/JBMtvnDTJMy/SztA/QbsckGWuzKnbmGGNkhQ4M1oZB17kulY5UHwNiiFxtOuRdwXZNjMOvKYN85nu9RchNWmhoAFYctP0ldHciYPK8jga/HmoWjQ20+mL6Yxx2NHETWiAx0Hy1pSiKETcGeF5QoRBpBe4z1JeoNA9EytIIg34AmODamCnf3q7giYd0YGGqUzDmam75k8T7tbWPF59KLJqO+gqNwJwDZucWhjjHG6JCZJihNL3OGr6XasdGx3FZmCchIO22jOF0gD1mjwrY8HDns28p8FMR2XvbsNKWjj9JiQZ/zObyLVaJG7RVCVlvqEPXivrco00OqO4j4IuOL3oB+yEhG/Vh48Z1QAHDZbHFT8cfa+Gk/i5dHbXdcs/+Nh18T3hdGyDFOeIu35EsZRVas1SvKPw3Z62Xu3z5VC5lCLJYjMXckudd4X2ksEVJ5Ax8nLX1nBiIEEdcmRoshm1hvCpaetKYs98JGxxNZzi1dSfxiK/L6NdlgT481i2RHGlxc6XudLpWcO5pao1Tx+D3rG/Y6gHfbc83DlvHjXZ3mtgPx9P4X5WJ7CcRDMaOoFQfcZdyTumIgqi5FYOasQ7HjdzhslQ=
  app : smart-bulb

